println(315.primeFactorMultiplicity)
// var now = System.currentTimeMillis()
// println(100090.totient)
// println("1: " + (System.currentTimeMillis() - now) + " ms.")
// now = System.currentTimeMillis()
// println(100090.totientImproved)
// println("2: " + (System.currentTimeMillis() - now) + " ms.")